In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

2.0.0-beta0
2.2.4-tf


模型堆叠

In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [7]:
# 网络层内写法

layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)

layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
# 注意如果用内置函数指定的话，intializers是复数

layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

训练和评估

In [8]:
model =tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer = tf.keras.optimizers.Adam(0.001),
            loss = tf.keras.losses.categorical_crossentropy,
             metrics=[tf.metrics.categorical_accuracy])

In [9]:
import numpy as np

train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))

val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs = 10, batch_size = 100,
         validation_data = (val_x, val_y))

W0625 12:18:56.898438  8768 deprecation.py:323] From C:\Users\ZSZ\Anaconda3\envs\tf2.0-beta\lib\site-packages\tensorflow\python\ops\math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 4s 4ms/sample - loss: 11.5758 - categorical_accuracy: 0.0990 - val_loss: 11.5831 - val_categorical_accuracy: 0.1250
Epoch 2/10
1000/1000 [==============================] - 0s 64us/sample - loss: 11.5452 - categorical_accuracy: 0.1090 - val_loss: 11.5679 - val_categorical_accuracy: 0.1200
Epoch 3/10
1000/1000 [==============================] - 0s 46us/sample - loss: 11.5365 - categorical_accuracy: 0.0950 - val_loss: 11.5605 - val_categorical_accuracy: 0.1150
Epoch 4/10
1000/1000 [==============================] - 0s 51us/sample - loss: 11.5312 - categorical_accuracy: 0.0870 - val_loss: 11.5576 - val_categorical_accuracy: 0.1350
Epoch 5/10
1000/1000 [==============================] - 0s 46us/sample - loss: 11.5280 - categorical_accuracy: 0.0890 - val_loss: 11.5556 - val_categorical_accuracy: 0.1300
Epoch 6/10
1000/1000 [==============================] - 0s 46us/sample - loss: 11.5249 - 

In [10]:
# 用tf.data输入数据

dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()

val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

In [12]:
model.fit(dataset, epochs=10, steps_per_epoch=20, shuffle = True,
         validation_data = val_dataset, validation_steps=3)

W0625 12:23:50.999273  8768 training_utils.py:1436] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
20/20 [==============================] - 0s 6ms/step - loss: 11.5215 - categorical_accuracy: 0.1688 - val_loss: 11.4934 - val_categorical_accuracy: 0.1146
Epoch 2/10
20/20 [==============================] - 0s 6ms/step - loss: 11.4923 - categorical_accuracy: 0.1364 - val_loss: 11.4887 - val_categorical_accuracy: 0.1354
Epoch 3/10
20/20 [==============================] - 0s 6ms/step - loss: 11.4762 - categorical_accuracy: 0.1422 - val_loss: 11.4928 - val_categorical_accuracy: 0.0729
Epoch 4/10
20/20 [==============================] - 0s 5ms/step - loss: 11.4550 - categorical_accuracy: 0.1802 - val_loss: 11.4967 - val_categorical_accuracy: 0.1042
Epoch 5/10
20/20 [==============================] - 0s 5ms/step - loss: 11.4626 - categorical_accuracy: 0.1445 - val_loss: 11.4927 - val_categorical_accuracy: 0.1250
Epoch 6/10
20/20 [==============================] - 0s 6ms/step - loss: 11.4816 - categorical_accuracy: 0.1578 - val_loss: 11.4949 - val_categorical_accuracy: 0.0833
Epoc

In [13]:
# 评估与预测

test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))

model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)

30/30 [==============================] - 0s 3ms/step - loss: 11.5817 - categorical_accuracy: 0.1104


[11.581687037150065, 0.110416666]

In [16]:
result = model.predict(test_x, batch_size=32)
print(result)

[[0.098343   0.10552397 0.12761746 ... 0.1213773  0.09635858 0.10230818]
 [0.10097872 0.11000811 0.08558819 ... 0.10391717 0.09740291 0.1035723 ]
 [0.10654136 0.0949679  0.11583142 ... 0.10366797 0.09467392 0.09472222]
 ...
 [0.10214821 0.10102384 0.09580076 ... 0.11671109 0.10111518 0.09210631]
 [0.10688464 0.10007742 0.0945962  ... 0.10281097 0.09613011 0.10199302]
 [0.11736409 0.09114841 0.11543581 ... 0.07312004 0.09009486 0.10564063]]


In [20]:
# 函数式api

#Sequential()只能简单地堆叠模型， 而函数式api可以构建复杂模型，例如多输入或多输出等等

input_x = tf.keras.Input(shape=(72, ))
hidden1 = layers.Dense(32, activation='relu')(input_x)
hidden2 = layers.Dense(16, activation='relu')(hidden1)
pred = layers.Dense(10, activation='softmax')(hidden2)


#定义模型输入和输出，中间层会被自动计算进去，因为他么么互相关联
model = tf.keras.Model(inputs = input_x, outputs=pred)
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss = tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 0s 299us/sample - loss: 11.5997 - accuracy: 0.1070
Epoch 2/5
1000/1000 [==============================] - 0s 131us/sample - loss: 11.5315 - accuracy: 0.0990
Epoch 3/5
1000/1000 [==============================] - 0s 126us/sample - loss: 11.5250 - accuracy: 0.0980
Epoch 4/5
1000/1000 [==============================] - 0s 121us/sample - loss: 11.5238 - accuracy: 0.1040
Epoch 5/5
1000/1000 [==============================] - 0s 128us/sample - loss: 11.5225 - accuracy: 0.1060


In [21]:
#  模型子类化  类似pytorch

class myModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(myModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.layer1  = layers.Dense(32, activation='relu')
        self.layer2 = layers.Dense(num_classes, activation='softmax')
        
    def call(self, inputs):
        h1 = self.layer1(inputs)
        out = self.layer2(h1)
        return out
    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1]=self.num_classes
        return tf.TensorShape(shape)
    
model = myModel(num_classes=10)
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics = ['accuracy'])
model.fit(train_x, train_y, batch_size=16, epochs=5)

Train on 1000 samples
Epoch 1/5
1000/1000 [==============================] - 1s 511us/sample - loss: 11.6047 - accuracy: 0.0970
Epoch 2/5
1000/1000 [==============================] - 0s 250us/sample - loss: 11.5298 - accuracy: 0.0960
Epoch 3/5
1000/1000 [==============================] - 0s 224us/sample - loss: 11.5237 - accuracy: 0.1070
Epoch 4/5
1000/1000 [==============================] - 0s 242us/sample - loss: 11.5205 - accuracy: 0.1110
Epoch 5/5
1000/1000 [==============================] - 0s 227us/sample - loss: 11.5174 - accuracy: 0.1110


In [25]:
# 回调
import os
logdir = 'callbacks'
if not os.path.exists(logdir):
    os.mkdir(logdir)
output_model_file = os.path.join(logdir,
                                'fashion_mnist_model.h5')

callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2, monitor='val_loss'),
    tf.keras.callbacks.TensorBoard(log_dir='logdir')
]
model.fit(train_x, train_y, batch_size=16, epochs=5,
         callbacks=callbacks, validation_data=(val_x,val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/5


W0625 12:56:39.348121  8768 callbacks.py:241] Method (on_train_batch_end) is slow compared to the batch update (0.351896). Check your callbacks.


  16/1000 [..............................] - ETA: 22s - loss: 11.6758 - accuracy: 0.0625

W0625 12:56:39.681230  8768 callbacks.py:241] Method (on_train_batch_end) is slow compared to the batch update (0.313089). Check your callbacks.


  32/1000 [..............................] - ETA: 20s - loss: 11.3598 - accuracy: 0.0625

W0625 12:56:39.688212  8768 callbacks.py:241] Method (on_train_batch_end) is slow compared to the batch update (0.274282). Check your callbacks.
W0625 12:56:39.695194  8768 callbacks.py:241] Method (on_train_batch_end) is slow compared to the batch update (0.137141). Check your callbacks.


1000/1000 [==============================] - 1s 1ms/sample - loss: 11.5157 - accuracy: 0.1190 - val_loss: 11.5518 - val_accuracy: 0.1000
Epoch 2/5
1000/1000 [==============================] - 0s 346us/sample - loss: 11.5131 - accuracy: 0.1190 - val_loss: 11.5506 - val_accuracy: 0.0950
Epoch 3/5
1000/1000 [==============================] - 0s 380us/sample - loss: 11.5108 - accuracy: 0.1230 - val_loss: 11.5521 - val_accuracy: 0.1300
Epoch 4/5
1000/1000 [==============================] - 0s 380us/sample - loss: 11.5079 - accuracy: 0.1260 - val_loss: 11.5519 - val_accuracy: 0.1200
